name: CI
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
        rails-version:
          - '6.0'
          - '6.1'
          - '7.0'
    name: 'Ruby ${{ matrix.ruby-version }}, Rails ${{ matrix.rails-version }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supercharge/mongodb-github-action@1.9.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ matrix.ruby-version }}'
          bundler-cache: true
        env:
          TEST_RAILS_VERSION: '${{ matrix.rails-version }}'
      - run: bundle exec rake
