name: CI
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # To keep matrix size down, only test highest and lowest rubies.
        ruby: ["3.0", "3.4"]
        rails: ["7.0", "7.1", "7.2", "8.0", "8.1"]
        exclude:
          - ruby: "3.0"
            rails: "7.2"
          - ruby: "3.0"
            rails: "8.0"
          - ruby: "3.0"
            rails: "8.1"
          - ruby: "3.4"
            rails: "7.0"
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v5
      - uses: supercharge/mongodb-github-action@1.12.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
